### ISSUE TITLE
managing multiple dataset versions

### ISSUE THREAD

**Issue by HeatherSavoy-USDA** [stuckyb/gcdl#100]
How should we track and implement multiple supported versions of a dataset? 

Right now, we have a dataset called DaymetV4 to indicate that we are using Version 4 of the dataset. But it is also the only version of the dataset we have. If V5 were to come out and we wanted to have both available to users, do we make a DaymetV5 dataset? That wouldn't be difficult on the user side. But would both versions live in [library/datasets/daymet.py](https://github.com/stuckyb/gcdl/blob/main/src/library/datasets/daymet.py) with the common attributes defined once and the individual attributes, e.g. filenames, be defined in separate classes? 

At the moment, I'm working on adding a SoilGrids dataset (#74). I'm focusing on the 250m Version 2 for now, but I'm assuming a new version will come out eventually so I want to plan ahead.

**Comment by stuckyb** [comment]
That is a great question. My first thought is that I'd be in favor of simply treating them as separate datasets, since they effectively are. I'm not sure we even need to bother with trying to share common attributes across different versions of a dataset, since many of those attributes are likely to differ (e.g., URLs, spatial resolution, etc.). That would be something we could address in a later refactoring if it became an issue.

**Comment by HeatherSavoy-USDA** [comment]
I'll just implement a `Soilgrids250mV2' dataset for now to indicate the specific version and not worry about other versions.
